# Generated by Django 4.2.27 on 2026-01-14 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, unique=True, verbose_name='Государственный номер')),
                ('year_out', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка/модель автобуса')),
                ('capacity', models.PositiveIntegerField(verbose_name='Количество пассажирских мест')),
            ],
            options={
                'verbose_name': 'Модель автобуса',
                'verbose_name_plural': 'Модели автобусов',
            },
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вокзала/станции')),
                ('address', models.CharField(max_length=255, verbose_name='Точный адрес')),
            ],
            options={
                'verbose_name': 'Автовокзал',
                'verbose_name_plural': 'Автовокзалы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО водителя')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Номер удостоверения')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расстояние (км)')),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_ends', to='station.busstation', verbose_name='Куда')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_starts', to='station.busstation', verbose_name='Откуда')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Пассажир'), ('manager', 'Диспетчер'), ('admin', 'Администратор')], default='client', max_length=10, verbose_name='Роль в системе')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон пассажира')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Дата и время отправления')),
                ('arrival_time', models.DateTimeField(verbose_name='Дата и время прибытия (расчетное)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.bus', verbose_name='Автобус')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.driver', verbose_name='Водитель')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Номер места в автобусе')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время покупки')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пассажир')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.trip', verbose_name='Поездка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к оплате')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('paid_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='station.ticket', verbose_name='К билету №')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='busstation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='bus',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='station.busmodel', verbose_name='Модель'),
        ),
    ]
