# Generated by Django 4.2.27 on 2026-01-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('sent', 'Отправлен'), ('cancelled', 'Отменен перевозчиком')], default='open', max_length=20, verbose_name='Состояние'),
        ),
    ]
