# Generated by Django 4.2.27 on 2026-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='platform',
            field=models.IntegerField(default=1, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('sent', 'Отправлен'), ('cancelled', 'Отменён перевозчиком')], default='open', max_length=20, verbose_name='Состояние'),
        ),
    ]
