# Generated by Django 4.2.27 on 2026-01-16 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_trip_platform_alter_trip_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='travel_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата поездки'),
            preserve_default=False,
        ),
    ]
