# Generated by Django 4.2.27 on 2026-01-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_ticket_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passport_series_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Серия и номер документа'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.PositiveIntegerField(verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='travel_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
